# Generated by Django 5.2.5 on 2025-10-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevision', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('derivacion', models.CharField(blank=True, max_length=50)),
                ('evaluacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('Alergia', models.CharField(blank=True, max_length=50)),
                ('motivoConsulta', models.CharField(blank=True, max_length=50)),
                ('frecuenciaCardiaca', models.CharField(max_length=50)),
                ('signosVitales', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('diabetes', models.CharField(max_length=20)),
                ('azucarEnSangre', models.CharField(max_length=10)),
                ('precionArterial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevision', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('derivacion', models.CharField(max_length=50)),
                ('evaluacion', models.CharField(max_length=50)),
                ('Alergia', models.CharField(max_length=50)),
                ('motivoConsulta', models.CharField(max_length=50)),
                ('frecuenciaCardiaca', models.CharField(max_length=50)),
                ('signosVitales', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('diabetes', models.CharField(max_length=50)),
                ('azucarEnSangre', models.CharField(max_length=50)),
                ('precionArterial', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datosMedicos.roles')),
            ],
        ),
    ]
