from django.core.management.base import BaseCommand
from ficha.models import Fichas, Usuario, HistorialAcciones

class Command(BaseCommand):
    help = 'Adds example Fichas to the database.'

    def handle(self, *args, **kwargs):
        example_fichas = [
            {
                'nombrepaciente': 'Juan',
                'apellidopaciente': 'Perez',
                'rutpaciente': '12.345.678-9',
                'rutparamedico': '98.765.432-1',
                'telefono': '912345678',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 30,
                'motivoconsulta': 'Caida Grave',
                'comorbilidades': '',
                'alergias': 'Penicilina',
                'frecuenciacardiaca': '72 bpm',
                'temperatura': '36.5 C',
                'presionarterial': '120/80 mmHg',
                'tiposangre': 'O+',
                'observaciones': 'Paciente en buen estado general.'
            },
            {
                'nombrepaciente': 'Maria',
                'apellidopaciente': 'Gonzalez',
                'rutpaciente': '23.456.789-0',
                'rutparamedico': '87.654.321-0',
                'telefono': '923456789',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 25,
                'motivoconsulta': 'Se quedo sin aire',
                'comorbilidades': 'Asma',
                'alergias': '',
                'frecuenciacardiaca': '80',
                'temperatura': '38.2',
                'presionarterial': '110',
                'tiposangre': 'A-',
                'observaciones': 'Requiere seguimiento por asma.'
            },
            {
                'nombrepaciente': 'Carlos',
                'apellidopaciente': 'Ramirez',
                'rutpaciente': '34.567.890-1',  
                'rutparamedico': '76.543.210-9',
                'telefono': '934567890',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 40,
                'motivoconsulta': 'Dolor abdominal',
                'comorbilidades': 'Diabetes',
                'alergias': '',
                'frecuenciacardiaca': '78',
                'temperatura': '37',
                'presionarterial': '130',
                'tiposangre': 'B+',
                'observaciones': 'Paciente con diabetes tipo 2.'
            },
            {
                'nombrepaciente': 'Ana',
                'apellidopaciente': 'Lopez',
                'rutpaciente': '45.678.901-2',
                'rutparamedico': '65.432.109-8',
                'telefono': '945678901',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 35,
                'motivoconsulta': 'Dolor de espalda',
                'comorbilidades': 'Hipertension',
                'alergias': 'Aspirina',
                'frecuenciacardiaca': '76',
                'temperatura': '36.8',
                'presionarterial': '140',
                'tiposangre': 'AB+',
                'observaciones': 'Requiere fisioterapia.'
            },
            {
                'nombrepaciente': 'Luis',
                'apellidopaciente': 'Martinez',
                'rutpaciente': '56.789.012-3',
                'rutparamedico': '54.321.098-7',
                'telefono': '956789012',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 28,
                'motivoconsulta': 'Esguince de tobillo derecho.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '74',
                'temperatura': '36.6',
                'presionarterial': '118',
                'tiposangre': 'O-',
                'observaciones': ''
            },
            {
                'nombrepaciente': 'Sofia',
                'apellidopaciente': 'Fernandez',
                'rutpaciente': '67.890.123-4',
                'rutparamedico': '43.210.987-6',
                'telefono': '967890123',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 32,
                'motivoconsulta': 'Fiebre alta y dolor de cabeza.',
                'comorbilidades': 'Migrañas',
                'alergias': '',
                'frecuenciacardiaca': '82',
                'temperatura': '39.0',
                'presionarterial': '115',
                'tiposangre': 'A+',
                'observaciones': 'Posible infección viral.'
            },
            {
                'nombrepaciente': 'Diego',
                'apellidopaciente': 'Sanchez',
                'rutpaciente': '78.901.234-5',
                'rutparamedico': '32.109.876-5',
                'telefono': '978901234',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 45,
                'motivoconsulta': 'Dolor en el pecho.',
                'comorbilidades': 'Colesterol alto',
                'alergias': '',
                'frecuenciacardiaca': '88',
                'temperatura': '37.2',
                'presionarterial': '150',
                'tiposangre': 'B-',
                'observaciones': 'Se recomienda realizar un electrocardiograma.'
            },
            {
                'nombrepaciente': 'Juan',
                'apellidopaciente': 'Perez',
                'rutpaciente': '12.345.678-9',
                'rutparamedico': '98.765.432-1',
                'telefono': '912345678',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 50,
                'motivoconsulta': 'Chequeo general.',
                'comorbilidades': 'Hipertension',
                'alergias': '',
                'frecuenciacardiaca': '80',
                'temperatura': '36.7',
                'presionarterial': '130',
                'tiposangre': 'A-',
                'observaciones': 'Paciente con hipertension controlada.'
            },
            {
                'nombrepaciente': 'Valentina',
                'apellidopaciente': 'Rojas',
                'rutpaciente': '89.012.345-6',
                'rutparamedico': '21.098.765-4',
                'telefono': '989012345',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 60,
                'motivoconsulta': 'Dolor articular en rodillas.',
                'comorbilidades': 'Artritis',
                'alergias': 'Ibuprofeno',
                'frecuenciacardiaca': '70',
                'temperatura': '36.4',
                'presionarterial': '125/85',
                'tiposangre': 'O+',
                'observaciones': 'Requiere derivación a reumatología.'
            },
            {
                'nombrepaciente': 'Pedro',
                'apellidopaciente': 'Castillo',
                'rutpaciente': '90.123.456-7',
                'rutparamedico': '10.987.654-3',
                'telefono': '990123456',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 52,
                'motivoconsulta': 'Tos persistente y dificultad para respirar.',
                'comorbilidades': 'Tabaquismo crónico',
                'alergias': '',
                'frecuenciacardiaca': '85',
                'temperatura': '37.8',
                'presionarterial': '135/90',
                'tiposangre': 'B+',
                'observaciones': 'Posible bronquitis crónica.'
            },
            {
                'nombrepaciente': 'Camila',
                'apellidopaciente': 'Diaz',
                'rutpaciente': '01.234.567-8',
                'rutparamedico': '09.876.543-2',
                'telefono': '901234567',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 19,
                'motivoconsulta': 'Dolor abdominal intenso.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '92',
                'temperatura': '38.5',
                'presionarterial': '110/70',
                'tiposangre': 'A+',
                'observaciones': 'Posible apendicitis, requiere evaluación quirúrgica.'
            },
            {
                'nombrepaciente': 'Ricardo',
                'apellidopaciente': 'Morales',
                'rutpaciente': '11.111.111-1',
                'rutparamedico': '22.222.222-2',
                'telefono': '911111111',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 70,
                'motivoconsulta': 'Chequeo post operatorio.',
                'comorbilidades': 'Hipertensión, diabetes',
                'alergias': 'Sulfas',
                'frecuenciacardiaca': '78',
                'temperatura': '36.6',
                'presionarterial': '145/95',
                'tiposangre': 'AB-',
                'observaciones': 'Paciente en recuperación tras cirugía cardíaca.'
            },
            {
                'nombrepaciente': 'Isabel',
                'apellidopaciente': 'Torres',
                'rutpaciente': '22.333.444-5',
                'rutparamedico': '33.444.555-6',
                'telefono': '922334445',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 45,
                'motivoconsulta': 'Dolor de cabeza recurrente.',
                'comorbilidades': 'Migrañas',
                'alergias': '',
                'frecuenciacardiaca': '75',
                'temperatura': '36.9',
                'presionarterial': '120/80',
                'tiposangre': 'O-',
                'observaciones': 'Se recomienda control neurológico.'

            },
            {
                'nombrepaciente': 'Juan',
                'apellidopaciente': 'Perez',
                'rutpaciente': '12.345.678-9',
                'rutparamedico': '98.765.432-1',
                'telefono': '912345678',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 51,
                'motivoconsulta': 'Dolor de cabeza persistente.',
                'comorbilidades': 'Hipertension',
                'alergias': '',
                'frecuenciacardiaca': '82',
                'temperatura': '37.0',
                'presionarterial': '135/85',
                'tiposangre': 'A-',
                'observaciones': 'Se recomienda control neurológico.'
            },
            {
                'nombrepaciente': 'Luis',
                'apellidopaciente': 'Martinez',
                'rutpaciente': '56.789.012-3',
                'rutparamedico': '54.321.098-7',
                'telefono': '956789012',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 29,
                'motivoconsulta': 'Dolor en rodilla izquierda.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '76',
                'temperatura': '36.5',
                'presionarterial': '118/78',
                'tiposangre': 'O-',
                'observaciones': 'Posible lesión meniscal, requiere resonancia.'
            },
            {
                'nombrepaciente': 'Maria',
                'apellidopaciente': 'Gonzalez',
                'rutpaciente': '23.456.789-0',
                'rutparamedico': '87.654.321-0',
                'telefono': '923456789',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 26,
                'motivoconsulta': 'Dolor torácico leve.',
                'comorbilidades': 'Asma',
                'alergias': '',
                'frecuenciacardiaca': '90',
                'temperatura': '36.9',
                'presionarterial': '120/80',
                'tiposangre': 'A-',
                'observaciones': 'Se indica radiografía de tórax.'
            },
            {
                'nombrepaciente': 'Carlos',
                'apellidopaciente': 'Ramirez',
                'rutpaciente': '34.567.890-1',
                'rutparamedico': '76.543.210-9',
                'telefono': '934567890',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 41,
                'motivoconsulta': 'Control rutinario de diabetes.',
                'comorbilidades': 'Diabetes tipo 2',
                'alergias': '',
                'frecuenciacardiaca': '80',
                'temperatura': '36.7',
                'presionarterial': '128/82',
                'tiposangre': 'B+',
                'observaciones': 'Paciente estable, requiere ajuste de dieta.'
            },
            {
                'nombrepaciente': 'Carlos',
                'apellidopaciente': 'Ramirez',
                'rutpaciente': '34.567.890-1',
                'rutparamedico': '76.543.210-9',
                'telefono': '934567890',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 43,
                'motivoconsulta': 'Chequeo general por diabetes.',
                'comorbilidades': 'Diabetes tipo 2',
                'alergias': '',
                'frecuenciacardiaca': '82',
                'temperatura': '36.7',
                'presionarterial': '130/85',
                'tiposangre': 'B+',
                'observaciones': 'Se mantiene tratamiento con insulina.'
            },
            {
                'nombrepaciente': 'Ana',
                'apellidopaciente': 'Lopez',
                'rutpaciente': '45.678.901-2',
                'rutparamedico': '65.432.109-8',
                'telefono': '945678901',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 36,
                'motivoconsulta': 'Dolor cervical tras accidente menor.',
                'comorbilidades': 'Hipertension',
                'alergias': 'Aspirina',
                'frecuenciacardiaca': '78',
                'temperatura': '36.8',
                'presionarterial': '138/88',
                'tiposangre': 'AB+',
                'observaciones': 'Se recomienda fisioterapia y analgésicos.'
            },
            {
                'nombrepaciente': 'Juan',
                'apellidopaciente': 'Perez',
                'rutpaciente': '12.345.678-9',
                'rutparamedico': '98.765.432-1',
                'telefono': '912345678',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 52,
                'motivoconsulta': 'Control de hipertensión.',
                'comorbilidades': 'Hipertension',
                'alergias': '',
                'frecuenciacardiaca': '79',
                'temperatura': '36.6',
                'presionarterial': '140/90',
                'tiposangre': 'A-',
                'observaciones': 'Se ajusta medicación antihipertensiva.'
            },
            {
                'nombrepaciente': 'Maria',
                'apellidopaciente': 'Gonzalez',
                'rutpaciente': '23.456.789-0',
                'rutparamedico': '87.654.321-0',
                'telefono': '923456789',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 27,
                'motivoconsulta': 'Crisis asmática leve.',
                'comorbilidades': 'Asma',
                'alergias': '',
                'frecuenciacardiaca': '95',
                'temperatura': '37.1',
                'presionarterial': '115/75',
                'tiposangre': 'A-',
                'observaciones': 'Se administra broncodilatador, paciente mejora.'
            },
            {
                'nombrepaciente': 'Carlos',
                'apellidopaciente': 'Ramirez',
                'rutpaciente': '34.567.890-1',
                'rutparamedico': '76.543.210-9',
                'telefono': '934567890',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 42,
                'motivoconsulta': 'Dolor abdominal recurrente.',
                'comorbilidades': 'Diabetes tipo 2',
                'alergias': '',
                'frecuenciacardiaca': '85',
                'temperatura': '37.5',
                'presionarterial': '132/84',
                'tiposangre': 'B+',
                'observaciones': 'Se solicita ecografía abdominal.'
            },
            {
                'nombrepaciente': 'Ana',
                'apellidopaciente': 'Lopez',
                'rutpaciente': '45.678.901-2',
                'rutparamedico': '65.432.109-8',
                'telefono': '945678901',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 37,
                'motivoconsulta': 'Dolor lumbar crónico.',
                'comorbilidades': 'Hipertension',
                'alergias': 'Aspirina',
                'frecuenciacardiaca': '77',
                'temperatura': '36.7',
                'presionarterial': '136/86',
                'tiposangre': 'AB+',
                'observaciones': 'Se indica terapia física prolongada.'
            },
            {
                'nombrepaciente': 'Luis',
                'apellidopaciente': 'Martinez',
                'rutpaciente': '56.789.012-3',
                'rutparamedico': '54.321.098-7',
                'telefono': '956789012',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 30,
                'motivoconsulta': 'Control post esguince.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '72',
                'temperatura': '36.5',
                'presionarterial': '120/80',
                'tiposangre': 'O-',
                'observaciones': 'Recuperación favorable, se autoriza actividad física leve.'
            },
            {
                'nombrepaciente': 'Juan',
                'apellidopaciente': 'Perez',
                'rutpaciente': '12.345.678-9',
                'rutparamedico': '98.765.432-1',
                'telefono': '912345678',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 53,
                'motivoconsulta': 'Dolor lumbar tras esfuerzo físico.',
                'comorbilidades': 'Hipertension',
                'alergias': '',
                'frecuenciacardiaca': '81',
                'temperatura': '36.8',
                'presionarterial': '138/88',
                'tiposangre': 'A-',
                'observaciones': 'Se recomienda reposo y analgésicos.'
            },
            {
                'nombrepaciente': 'Maria',
                'apellidopaciente': 'Gonzalez',
                'rutpaciente': '23.456.789-0',
                'rutparamedico': '87.654.321-0',
                'telefono': '923456789',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 28,
                'motivoconsulta': 'Control post crisis asmática.',
                'comorbilidades': 'Asma',
                'alergias': '',
                'frecuenciacardiaca': '88',
                'temperatura': '36.9',
                'presionarterial': '118/76',
                'tiposangre': 'A-',
                'observaciones': 'Paciente estable, se indica inhalador preventivo.'
            },
            {
                'nombrepaciente': 'Ana',
                'apellidopaciente': 'Lopez',
                'rutpaciente': '45.678.901-2',
                'rutparamedico': '65.432.109-8',
                'telefono': '945678901',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 38,
                'motivoconsulta': 'Dolor cervical crónico.',
                'comorbilidades': 'Hipertension',
                'alergias': 'Aspirina',
                'frecuenciacardiaca': '75',
                'temperatura': '36.6',
                'presionarterial': '135/85',
                'tiposangre': 'AB+',
                'observaciones': 'Se recomienda terapia física y control médico.'
            },
            {
                'nombrepaciente': 'Luis',
                'apellidopaciente': 'Martinez',
                'rutpaciente': '56.789.012-3',
                'rutparamedico': '54.321.098-7',
                'telefono': '956789012',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 31,
                'motivoconsulta': 'Dolor en tobillo tras actividad deportiva.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '78',
                'temperatura': '36.5',
                'presionarterial': '119/79',
                'tiposangre': 'O-',
                'observaciones': 'Se indica reposo y hielo local.'
            },
            {
                'nombrepaciente': 'Claudia',
                'apellidopaciente': 'Mendez',
                'rutpaciente': '66.777.888-9',
                'rutparamedico': '44.555.666-7',
                'telefono': '966777888',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 48,
                'motivoconsulta': 'Dolor en articulaciones.',
                'comorbilidades': 'Artritis reumatoide',
                'alergias': 'Diclofenaco',
                'frecuenciacardiaca': '74',
                'temperatura': '36.6',
                'presionarterial': '125/80',
                'tiposangre': 'O+',
                'observaciones': 'Requiere control con reumatología.'
            },
            {
                'nombrepaciente': 'Felipe',
                'apellidopaciente': 'Navarro',
                'rutpaciente': '77.888.999-0',
                'rutparamedico': '55.666.777-8',
                'telefono': '977888999',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 22,
                'motivoconsulta': 'Fractura en brazo derecho.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '85',
                'temperatura': '37.0',
                'presionarterial': '118/75',
                'tiposangre': 'B+',
                'observaciones': 'Se inmoviliza con yeso, requiere control ortopédico.'
            },
            {
                'nombrepaciente': 'Patricia',
                'apellidopaciente': 'Silva',
                'rutpaciente': '88.999.000-1',
                'rutparamedico': '66.777.888-9',
                'telefono': '988999000',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 55,
                'motivoconsulta': 'Dolor torácico agudo.',
                'comorbilidades': 'Hipertensión, colesterol alto',
                'alergias': '',
                'frecuenciacardiaca': '92',
                'temperatura': '37.2',
                'presionarterial': '150/95',
                'tiposangre': 'A+',
                'observaciones': 'Se indica electrocardiograma urgente.'
            },
            {
                'nombrepaciente': 'Andres',
                'apellidopaciente': 'Vega',
                'rutpaciente': '99.000.111-2',
                'rutparamedico': '77.888.999-0',
                'telefono': '999000111',
                'prevision': 'Fonasa',
                'genero': 'masculino',
                'edad': 33,
                'motivoconsulta': 'Fiebre alta y tos.',
                'comorbilidades': '',
                'alergias': '',
                'frecuenciacardiaca': '90',
                'temperatura': '39.5',
                'presionarterial': '120/80',
                'tiposangre': 'O-',
                'observaciones': 'Posible neumonía, requiere antibióticos.'
            },
            {
                'nombrepaciente': 'Gabriela',
                'apellidopaciente': 'Castro',
                'rutpaciente': '10.111.222-3',
                'rutparamedico': '88.999.000-1',
                'telefono': '910111222',
                'prevision': 'Isapre',
                'genero': 'femenino',
                'edad': 29,
                'motivoconsulta': 'Dolor abdominal intenso.',
                'comorbilidades': '',
                'alergias': 'Mariscos',
                'frecuenciacardiaca': '95',
                'temperatura': '38.7',
                'presionarterial': '110/70',
                'tiposangre': 'AB-',
                'observaciones': 'Se sospecha apendicitis, derivada a cirugía.'
            }

        ]

        for ficha_data in example_fichas:
            Fichas.objects.create(**ficha_data)

        self.stdout.write(self.style.SUCCESS('Example Fichas have been added successfully.'))

