# Generated by Django 5.2.7 on 2025-10-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepaciente', models.CharField(max_length=50)),
                ('apellidopaciente', models.CharField(max_length=50)),
                ('rutpaciente', models.CharField(max_length=12, unique=True)),
                ('rutparamedico', models.CharField(max_length=12)),
                ('telefono', models.IntegerField()),
                ('prevision', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('motivoconsulta', models.CharField(max_length=100)),
                ('comorbilidades', models.CharField(max_length=50)),
                ('alergias', models.CharField(max_length=50)),
                ('frecuenciacardiaca', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('presionarterial', models.CharField(max_length=50)),
                ('tiposangre', models.CharField(max_length=5)),
                ('observaciones', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
    ]
