# Generated by Django 5.2.7 on 2025-10-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='rutpaciente',
            field=models.CharField(max_length=12),
        ),
    ]
