# Generated by Django 5.2.7 on 2025-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_alter_fichas_rutpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='alergias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='apellidopaciente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='comorbilidades',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='frecuenciacardiaca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='genero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='motivoconsulta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='nombrepaciente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='presionarterial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='prevision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='rutpaciente',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='rutparamedico',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='tiposangre',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
