# Generated by Django 5.2.7 on 2025-10-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_alter_fichas_alergias_alter_fichas_apellidopaciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
