# Generated by Django 5.2.7 on 2025-10-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_alter_fichas_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='telefono',
            field=models.CharField(default='', max_length=9),
        ),
    ]
