# Generated by Django 5.2.7 on 2025-11-12 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_historialacciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
