# Generated by Django 5.2.7 on 2025-11-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_usuario_apellido_usuario_bio_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
