# Generated by Django 5.2.7 on 2025-11-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_fichas_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacciones',
            name='cambios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
