# Generated by Django 5.2.7 on 2025-11-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_historialacciones_cambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacciones',
            name='cambios',
            field=models.JSONField(default=None),
        ),
    ]
