# Generated by Django 5.2.7 on 2025-11-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_alter_historialacciones_cambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacciones',
            name='accion',
            field=models.CharField(max_length=1000),
        ),
    ]
