# Generated by Django 5.2.7 on 2025-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0017_alter_fichas_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='apellidopaciente',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='nombrepaciente',
            field=models.CharField(default='', max_length=80),
        ),
    ]
