# Generated by Django 5.2.7 on 2025-11-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0018_alter_fichas_apellidopaciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotodeperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
