# Generated by Django 5.2.7 on 2025-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
