# Generated by Django 5.2.7 on 2025-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0016_alter_historialacciones_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='observaciones',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
