# Generated by Django 5.2.5 on 2025-11-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0019_usuario_fotodeperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fotodeperfil',
        ),
    ]
